import { jsPDF } from 'jspdf';
import type { DocumentAnalysis } from './documentAnalyzer';
import type { Tier } from './complexityContent';

const BRAND = 'LegalLens AI';
const FOOTER = 'Generated by LegalLens AI  •  legallens.ai';

// ─── Colour palette ───────────────────────────────────────────────────────────
const C = {
  primary:   [37,  99, 235] as [number, number, number],   // blue-600
  purple:    [147, 51, 234] as [number, number, number],   // purple-600
  dark:      [15,  23,  42] as [number, number, number],   // slate-900
  mid:       [71,  85, 105] as [number, number, number],   // slate-600
  light:     [241,245,249] as [number, number, number],    // slate-100
  white:     [255,255,255] as [number, number, number],
  red:       [220,  38,  38] as [number, number, number],
  yellow:    [202,138,   4] as [number, number, number],
  green:     [ 22,163,  74] as [number, number, number],
  amber:     [217,119,   6] as [number, number, number],
};

// ─── Layout constants ─────────────────────────────────────────────────────────
const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;
const FOOTER_Y = PAGE_H - 10;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function rgb(doc: jsPDF, color: [number, number, number]) {
  doc.setTextColor(color[0], color[1], color[2]);
}

function fill(doc: jsPDF, color: [number, number, number]) {
  doc.setFillColor(color[0], color[1], color[2]);
}

function drawFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  doc.setFontSize(8);
  rgb(doc, C.mid);
  doc.setFont('helvetica', 'normal');
  doc.text(FOOTER, MARGIN, FOOTER_Y);
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - MARGIN, FOOTER_Y, { align: 'right' });
  // thin rule above footer
  doc.setDrawColor(C.mid[0], C.mid[1], C.mid[2]);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, FOOTER_Y - 3, PAGE_W - MARGIN, FOOTER_Y - 3);
}

/** Wrap text and return new Y position */
function writeWrapped(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
): number {
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

/** Draw a section heading pill */
function sectionHeading(doc: jsPDF, label: string, y: number): number {
  fill(doc, C.light);
  doc.roundedRect(MARGIN, y, CONTENT_W, 8, 2, 2, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  rgb(doc, C.primary);
  doc.text(label.toUpperCase(), MARGIN + 4, y + 5.5);
  return y + 12;
}

/** Severity dot colour */
function severityColor(sev: string): [number, number, number] {
  if (sev === 'high')   return C.red;
  if (sev === 'medium') return C.yellow;
  return C.green;
}

/** Guidance type colour */
function guidanceColor(type: string): [number, number, number] {
  if (type === 'redflag')    return C.red;
  if (type === 'warning')    return C.amber;
  if (type === 'safety')     return C.primary;
  return C.purple;
}

function guidanceIcon(type: string): string {
  if (type === 'redflag')    return '[!]';
  if (type === 'warning')    return '[W]';
  if (type === 'safety')     return '[S]';
  return '[*]';
}

/** Check if we need a new page; add one if so */
function checkPage(doc: jsPDF, y: number, needed = 14): { doc: jsPDF; y: number; newPage: boolean } {
  if (y + needed > FOOTER_Y - 8) {
    doc.addPage();
    return { doc, y: MARGIN + 4, newPage: true };
  }
  return { doc, y, newPage: false };
}

// ─── Main export ──────────────────────────────────────────────────────────────

export function generatePDFReport(analysis: DocumentAnalysis, tier: Tier): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // ── Cover / header ──────────────────────────────────────────────────────
  // Gradient-style header bar
  fill(doc, C.primary);
  doc.rect(0, 0, PAGE_W, 38, 'F');
  fill(doc, C.purple);
  doc.rect(PAGE_W - 60, 0, 60, 38, 'F');

  // Brand name
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  rgb(doc, C.white);
  doc.text(BRAND, MARGIN, 16);

  // Subtitle
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Document Analysis Report', MARGIN, 23);
  doc.text(`Generated: ${date}`, MARGIN, 29);

  // Recommendation badge (top-right)
  const recLabel = analysis.recommendation === 'safe'
    ? 'SAFE TO SIGN'
    : analysis.recommendation === 'review'
    ? 'REVIEW CAREFULLY'
    : 'NOT RECOMMENDED';
  const recColor: [number, number, number] = analysis.recommendation === 'safe'
    ? C.green
    : analysis.recommendation === 'review'
    ? C.yellow
    : C.red;

  fill(doc, recColor);
  doc.roundedRect(PAGE_W - MARGIN - 46, 8, 46, 10, 2, 2, 'F');
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  rgb(doc, C.white);
  doc.text(recLabel, PAGE_W - MARGIN - 23, 14.5, { align: 'center' });

  let y = 46;

  // ── Document title block ────────────────────────────────────────────────
  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  rgb(doc, C.dark);
  doc.text(analysis.title || 'Untitled Document', MARGIN, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  rgb(doc, C.mid);
  doc.text(`${analysis.documentType}  •  Parties: ${analysis.parties.join(' and ')}`, MARGIN, y);
  y += 4;

  // Risk score bar
  const barW = 80;
  const barH = 4;
  fill(doc, C.light);
  doc.roundedRect(MARGIN, y, barW, barH, 1, 1, 'F');
  const scoreW = (analysis.riskScore / 100) * barW;
  fill(doc, analysis.riskScore >= 70 ? C.red : analysis.riskScore >= 35 ? C.yellow : C.green);
  doc.roundedRect(MARGIN, y, scoreW, barH, 1, 1, 'F');
  doc.setFontSize(8);
  rgb(doc, C.mid);
  doc.text(`Risk Score: ${analysis.riskScore}/100`, MARGIN + barW + 3, y + 3);
  y += 10;

  // thin divider
  doc.setDrawColor(C.light[0], C.light[1], C.light[2]);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  // ── 1. Summary ──────────────────────────────────────────────────────────
  y = sectionHeading(doc, '1. Summary', y);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  rgb(doc, C.dark);
  const summaryText = analysis.summaries[tier] || 'Not available';
  y = writeWrapped(doc, summaryText, MARGIN, y, CONTENT_W, 5);
  y += 6;

  // ── 2. Risk Assessment ──────────────────────────────────────────────────
  ({ y } = checkPage(doc, y, 20));
  y = sectionHeading(doc, '2. Risk Assessment', y);

  for (const risk of analysis.risks) {
    ({ y } = checkPage(doc, y, 18));
    const col = severityColor(risk.severity);

    // Severity dot
    fill(doc, col);
    doc.circle(MARGIN + 2, y + 1.5, 1.5, 'F');

    // Title
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    rgb(doc, C.dark);
    doc.text(risk.title, MARGIN + 6, y + 3);

    // Severity badge
    fill(doc, col);
    doc.roundedRect(PAGE_W - MARGIN - 22, y - 0.5, 22, 5.5, 1.5, 1.5, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    rgb(doc, C.white);
    doc.text(risk.severity.toUpperCase(), PAGE_W - MARGIN - 11, y + 3, { align: 'center' });

    y += 6;

    // Description
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    rgb(doc, C.mid);
    y = writeWrapped(doc, risk.desc, MARGIN + 6, y, CONTENT_W - 6, 4.5);

    // Verbatim clause excerpt
    if (risk.clause && risk.clause.length > 5) {
      ({ y } = checkPage(doc, y, 10));
      fill(doc, C.light);
      const clauseLines = doc.splitTextToSize(`"${risk.clause}"`, CONTENT_W - 12);
      const boxH = clauseLines.length * 4 + 4;
      doc.roundedRect(MARGIN + 6, y, CONTENT_W - 6, boxH, 1.5, 1.5, 'F');
      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'italic');
      rgb(doc, C.mid);
      doc.text(clauseLines, MARGIN + 9, y + 4);
      y += boxH + 2;
    }

    // KB badge
    if (risk.kbPatternId) {
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      rgb(doc, C.primary);
      doc.text(`KB Pattern ${risk.kbPatternId}  •  ${Math.round((risk.kbSimilarity ?? 0) * 100)}% match`, MARGIN + 6, y);
      y += 4;
    }

    y += 3;
  }
  y += 2;

  // ── 3. User Obligations ─────────────────────────────────────────────────
  ({ y } = checkPage(doc, y, 20));
  y = sectionHeading(doc, '3. User Obligations', y);
  const obligations = analysis.obligations[tier];
  for (const ob of obligations) {
    ({ y } = checkPage(doc, y, 10));
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    rgb(doc, C.dark);
    fill(doc, C.primary);
    doc.circle(MARGIN + 2, y + 1.5, 1, 'F');
    y = writeWrapped(doc, ob, MARGIN + 6, y, CONTENT_W - 6, 4.5);
    y += 2;
  }
  y += 4;

  // ── 4. Important Clauses ────────────────────────────────────────────────
  ({ y } = checkPage(doc, y, 20));
  y = sectionHeading(doc, '4. Important Clauses', y);
  for (const clause of analysis.importantClauses) {
    ({ y } = checkPage(doc, y, 12));
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'bold');
    rgb(doc, C.dark);
    doc.text(`${clause.label}:`, MARGIN, y + 3);

    doc.setFont('helvetica', 'normal');
    rgb(doc, clause.value === 'Not specified in document' ? C.mid : C.dark);
    const valLines = doc.splitTextToSize(clause.value, CONTENT_W - 38);
    doc.text(valLines, MARGIN + 38, y + 3);
    y += valLines.length * 4.5 + 3;
  }
  y += 4;

  // ── 5. Decision Recommendation ──────────────────────────────────────────
  ({ y } = checkPage(doc, y, 24));
  y = sectionHeading(doc, '5. Decision Recommendation', y);

  fill(doc, analysis.recommendation === 'safe' ? [240,253,244] : analysis.recommendation === 'review' ? [254,252,232] : [254,242,242]);
  const recBoxH = 20;
  doc.roundedRect(MARGIN, y, CONTENT_W, recBoxH, 2, 2, 'F');

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  rgb(doc, recColor);
  doc.text(recLabel, MARGIN + 4, y + 7);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  rgb(doc, C.dark);
  const reasonLines = doc.splitTextToSize(analysis.recommendationReason || 'Not available', CONTENT_W - 8);
  doc.text(reasonLines, MARGIN + 4, y + 13);
  y += recBoxH + 8;

  // ── 6. Guidance & Safety Recommendations ───────────────────────────────
  if (analysis.guidance && analysis.guidance.length > 0) {
    ({ y } = checkPage(doc, y, 20));
    y = sectionHeading(doc, '6. Guidance & Safety Recommendations', y);

    for (const item of analysis.guidance) {
      ({ y } = checkPage(doc, y, 16));
      const col = guidanceColor(item.type);
      const icon = guidanceIcon(item.type);

      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'bold');
      rgb(doc, col);
      doc.text(icon, MARGIN, y + 3);

      doc.setFont('helvetica', 'normal');
      rgb(doc, C.dark);
      const itemLines = doc.splitTextToSize(item.text, CONTENT_W - 10);
      doc.text(itemLines, MARGIN + 8, y + 3);
      y += itemLines.length * 4.5 + 3;

      // Priority tag
      doc.setFontSize(7);
      rgb(doc, C.mid);
      doc.text(`Priority: ${item.priority.toUpperCase()}`, MARGIN + 8, y);
      y += 5;
    }
    y += 2;
  }

  // ── 7. Actionable Suggestions ───────────────────────────────────────────
  if (analysis.suggestions && analysis.suggestions.length > 0) {
    ({ y } = checkPage(doc, y, 20));
    y = sectionHeading(doc, '7. Actionable Suggestions', y);
    for (const s of analysis.suggestions) {
      ({ y } = checkPage(doc, y, 10));
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      rgb(doc, C.dark);
      fill(doc, C.purple);
      doc.circle(MARGIN + 2, y + 1.5, 1, 'F');
      y = writeWrapped(doc, s, MARGIN + 6, y, CONTENT_W - 6, 4.5);
      y += 2;
    }
  }

  // ── Footer on all pages ─────────────────────────────────────────────────
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawFooter(doc, i, totalPages);
  }

  // ── Save ────────────────────────────────────────────────────────────────
  const safeName = (analysis.title || 'Document')
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim()
    .replace(/\s+/g, '_')
    .slice(0, 40);
  doc.save(`LegalLens_Report_${safeName}.pdf`);
}
